### ISSUE TITLE
'class WiFiManager' has no member named 'useLittleFS'

### ISSUE THREAD

**Issue by trombose009** [ElToberino/Tobers_Timeswitch#1]
I get 
'class WiFiManager' has no member named 'useLittleFS'
if I want to compile it. Whatam I doing wrong?

**Comment by ElToberino** [comment]
Sorry for the late answer.
You must have installed the current version of [my own WifiManger fork](https://github.com/ElToberino/WiFiManager_for_Multidisplay) - **and this is important**: You can't have both WifiManager Versions in your libraries directory!
So please move the "normal WifiManager" out of your library folder while using my fork.
Best regards!
